services:
  postgres:
    image: postgres:15
    container_name: task-tracker-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: task-tracker-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: postgres
      KEYCLOAK_ADMIN_PASSWORD: postgres

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_HOSTNAME: localhost

    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: task-tracker-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/task-tracker-realm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/task-tracker-realm/protocol/openid-connect/certs

      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

    ports:
      - "8081:8081"
      - "5005:5005"
    depends_on:
      - postgres
      - keycloak
    extra_hosts:
      - "localhost:host-gateway"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: task-tracker-ui
    ports:
      - "8082:80"
    depends_on:
      - api
      - keycloak

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
