services:
  postgres:
    image: postgres:15
    container_name: task-tracker-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: task-tracker-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin

      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: task-tracker-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_tracker
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/task-tracker-realm
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - keycloak

volumes:
  postgres_data:
